/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x36, 0x1E, 0x8A, 0xCF, 0x5C, 0x35, 0x67, 0xCC}

#define DYNAMIC_KEYMAP_LAYER_COUNT 2

#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, KC_BRID, KC_BRIU }
#define VIAL_ENCODER_KEYCODE_DELAY 10

#define RGBLIGHT_LAYERS
